[sysvinit] Move rc back to this package (from initscripts)

diff --git a/meta-oe/recipes-core/sysvinit/sysvinit/rc b/meta-oe/recipes-core/sysvinit/sysvinit/rc
--- a/meta-oe/recipes-core/sysvinit/sysvinit/rc
+++ b/meta-oe/recipes-core/sysvinit/sysvinit/rc
@@ -1,188 +1,261 @@
-#!/bin/sh
+#! /bin/sh
 #
-# rc		This file is responsible for starting/stopping
-#		services when the runlevel changes.
+# rc
 #
-#		Optimization feature:
-#		A startup script is _not_ run when the service was
-#		running in the previous runlevel and it wasn't stopped
-#		in the runlevel transition (most Debian services don't
-#		have K?? links in rc{1,2,3,4,5} )
+# Starts/stops services on runlevel changes.
 #
-# Author:	Miquel van Smoorenburg <miquels@cistron.nl>
-#		Bruce Perens <Bruce@Pixar.com>
+# Optimization: A start script is not run when the service was already
+# configured to run in the previous runlevel.  A stop script is not run
+# when the the service was already configured not to run in the previous
+# runlevel.
 #
-# Version:	@(#)rc  2.78  07-Nov-1999  miquels@cistron.nl
-#
+# Authors:
+# 	Miquel van Smoorenburg <miquels@cistron.nl>
+# 	Bruce Perens <Bruce@Pixar.com>
 
-. /etc/default/rcS
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+export PATH
+
+# Un-comment the following for interactive debugging. Do not un-comment
+# this for debugging a real boot process as no scripts will be executed.
+# debug=echo
+
+# Make sure the name survive changing the argument list
+scriptname="$0"
+
+umask 022
+
+on_exit() {
+	echo "error: '$scriptname' exited outside the expected code flow."
+}
+trap on_exit EXIT # Enable emergency handler
+
+# Ignore CTRL-C only in this shell, so we can interrupt subprocesses.
+trap ":" INT QUIT TSTP
+
+# Set onlcr to avoid staircase effect.
+stty onlcr 0>&1
+
+# Now find out what the current and what the previous runlevel are.
+
+runlevel=$RUNLEVEL
+# Get first argument. Set new runlevel to this argument.
+[ "$1" != "" ] && runlevel=$1
+if [ "$runlevel" = "" ]
+then
+	echo "Usage: $scriptname <runlevel>" >&2
+	exit 1
+fi
+previous=$PREVLEVEL
+[ "$previous" = "" ] && previous=N
+
+export runlevel previous
+
+if [ -f /etc/default/rcS ] ; then
+	. /etc/default/rcS
+fi
 export VERBOSE
 
-startup_progress() {
-    step=$(($step + $step_change))
-    if [ "$num_steps" != "0" ]; then
-        progress=$((($step * $progress_size / $num_steps) + $first_step))
-    else
-        progress=$progress_size
-    fi
-    #echo "PROGRESS is $progress $runlevel $first_step + ($step of $num_steps) $step_change $progress_size"
-    #if type psplash-write >/dev/null 2>&1; then
-    #    TMPDIR=/mnt/.psplash psplash-write "PROGRESS $progress" || true
-    #fi
-    if [ $progress -gt 0 -a -e /proc/progress ]; then
-        echo $(($progress / 2)) > /proc/progress
-    elif [ $progress -gt 0 -a -e /proc/vfd ]; then
-        echo Loading $(($progress / 2)) % > /proc/vfd
-    elif [ $progress -gt 0 -a -e /usr/bin/displayvfd ]; then
-        displayvfd -s 18 -t "Booting $progress"
-    elif [ $progress -gt 0 -a -e /dev/mcu ]; then
-        echo $(($progress / 2)) > /dev/mcu
-    fi
-}
+if [ -f /lib/lsb/init-functions ] ; then
+	. /lib/lsb/init-functions
+else
+	log_action_msg() { echo $@; }
+	log_failure_msg() { echo $@; }
+	log_warning_msg() { echo $@; }
+fi
 
+#
+# Check if we are able to use make like booting.  It require the
+# insserv package to be enabled. Boot concurrency also requires
+# startpar to be installed.
+#
+CONCURRENCY=makefile
+test -s /etc/init.d/.depend.boot  || CONCURRENCY="none"
+test -s /etc/init.d/.depend.start || CONCURRENCY="none"
+test -s /etc/init.d/.depend.stop  || CONCURRENCY="none"
+if test -e /etc/init.d/.legacy-bootordering ; then
+	CONCURRENCY="none"
+fi
+if ! test -e /proc/stat; then
+	if [ "$(uname)" = "GNU/kFreeBSD" ] ; then
+		# startpar requires /proc/stat
+		mount -t linprocfs linprocfs /proc
+	fi
+fi
+if [ -x /lib/startpar/startpar ] ; then
+    STARTPAR=/lib/startpar/startpar
+else
+    STARTPAR=startpar
+fi
+$STARTPAR -v > /dev/null 2>&1 || CONCURRENCY="none"
 
 #
 # Start script or program.
 #
-startup() {
-  # Handle verbosity
-  [ "$VERBOSE" = very ] && echo "INIT: Running $@..."
+case "$CONCURRENCY" in
+	makefile|startpar|shell) # startpar and shell are obsolete
+		CONCURRENCY=makefile
+		log_action_msg "Using makefile-style concurrent boot in runlevel $runlevel"
+		startup() {
+			eval "$($STARTPAR -p 4 -t 20 -T 3 -M $1 -P $previous -R $runlevel)"
 
-  case "$1" in
-	*.sh)
-		# Source shell script for speed.
-		(
-			trap - INT QUIT TSTP
-			scriptname=$1
+			if [ -n "$failed_service" ]
+			then
+				log_failure_msg "startpar: service(s) returned failure: $failed_service"
+			fi
+
+			if [ -n "$skipped_service_not_installed" ]
+			then
+				log_warning_msg "startpar: service(s) skipped, program is not installed: $skipped_service_not_installed"
+			fi
+
+			if [ -n "$skipped_service_not_configured" ]
+			then
+				log_warning_msg "startpar: service(s) skipped, program is not configured: $skipped_service_not_configured"
+			fi
+
+			unset failed_service skipped_service_not_installed skipped_service_not_configured
+		}
+		;;
+	none|*)
+		startup() {
+			action=$1
 			shift
-			. $scriptname
-		)
+			scripts="$@"
+			for script in $scripts ; do
+				$debug "$script" $action
+			done
+		}
 		;;
-	*)
-		"$@"
-		;;
-  esac
-  startup_progress
-}
+esac
 
-  # Ignore CTRL-C only in this shell, so we can interrupt subprocesses.
-  trap ":" INT QUIT TSTP
-
-  # Set onlcr to avoid staircase effect.
-  stty onlcr 0>&1
-
-  # Limit stack size for startup scripts
-  [ "$STACK_SIZE" == "" ] || ulimit -S -s $STACK_SIZE
-
-  # Now find out what the current and what the previous runlevel are.
-
-  runlevel=$RUNLEVEL
-  # Get first argument. Set new runlevel to this argument.
-  [ "$1" != "" ] && runlevel=$1
-  if [ "$runlevel" = "" ]
-  then
-	echo "Usage: $0 <runlevel>" >&2
-	exit 1
-  fi
-  previous=$PREVLEVEL
-  [ "$previous" = "" ] && previous=N
-
-  export runlevel previous
-
-  # Is there an rc directory for this new runlevel?
-  if [ -d /etc/rc$runlevel.d ]
-  then
-	# Find out where in the progress bar the initramfs got to.
-	PROGRESS_STATE=0
-	#if [ -f /dev/.initramfs/progress_state ]; then
-	#    . /dev/.initramfs/progress_state
-	#fi
-
-	# Split the remaining portion of the progress bar into thirds
-	progress_size=$(((100 - $PROGRESS_STATE) / 3))
-
+# Is there an rc directory for this new runlevel?
+if [ -d /etc/rc$runlevel.d ]
+then
 	case "$runlevel" in
 		0|6)
-			# Count down from -100 to 0 and use the entire bar
-			first_step=-100
-			progress_size=100
-			step_change=1
+			ACTION=stop
 			;;
-	        S)
-			# Begin where the initramfs left off and use 2/3
-			# of the remaining space
-			first_step=$PROGRESS_STATE
-			progress_size=$(($progress_size * 2))
-			step_change=1
+		S)
+			ACTION=start
 			;;
 		*)
-			# Begin where rcS left off and use the final 1/3 of
-			# the space (by leaving progress_size unchanged)
-			first_step=$(($progress_size * 2 + $PROGRESS_STATE))
-			step_change=1
+			ACTION=start
 			;;
 	esac
 
-	num_steps=0
-	for s in /etc/rc$runlevel.d/[SK]*; do
-            case "${s##/etc/rc$runlevel.d/S??}" in
-                gdm|xdm|kdm|reboot|halt)
-                    break
-                    ;;
-            esac
-            num_steps=$(($num_steps + 1))
-        done
-        step=0
-
 	# First, run the KILL scripts.
-	if [ $previous != N ]
+	if [ makefile = "$CONCURRENCY" ]
 	then
-		for i in /etc/rc$runlevel.d/K[0-9][0-9]*
+		if [ "$ACTION" = "start" ] && [ "$previous" != N ]
+		then
+			startup stop
+		fi
+	elif [ "$previous" != N ]
+	then
+		# Run all scripts with the same level in parallel
+		CURLEVEL=""
+		for s in /etc/rc$runlevel.d/K*
 		do
-			# Check if the script is there.
-			[ ! -f $i ] && continue
+			# Extract order value from symlink
+			level=${s#/etc/rc$runlevel.d/K}
+			level=${level%%[a-zA-Z]*}
+			if [ "$level" = "$CURLEVEL" ]
+			then
+				continue
+			fi
+			CURLEVEL=$level
+			SCRIPTS=""
+			for i in /etc/rc$runlevel.d/K$level*
+			do
+				# Check if the script is there.
+				[ ! -f $i ] && continue
 
-			# Stop the service.
-			startup $i stop
+				#
+				# Find stop script in previous runlevel but
+				# no start script there.
+				#
+				suffix=${i#/etc/rc$runlevel.d/K[0-9][0-9]}
+				previous_stop=/etc/rc$previous.d/K[0-9][0-9]$suffix
+				previous_start=/etc/rc$previous.d/S[0-9][0-9]$suffix
+				#
+				# If there is a stop script in the previous level
+				# and _no_ start script there, we don't
+				# have to re-stop the service.
+				#
+				[ -f $previous_stop ] && [ ! -f $previous_start ] && continue
+
+				# Stop the service.
+				SCRIPTS="$SCRIPTS $i"
+			done
+			startup stop $SCRIPTS
 		done
 	fi
 
-	# Now run the START scripts for this runlevel.
-	for i in /etc/rc$runlevel.d/S*
-	do
-		[ ! -f $i ] && continue
-
-		if [ $previous != N ] && [ $previous != S ]
+	if [ makefile = "$CONCURRENCY" ]
+	then
+		if [ S = "$runlevel" ]
 		then
-			#
-			# Find start script in previous runlevel and
-			# stop script in this runlevel.
-			#
-			suffix=${i#/etc/rc$runlevel.d/S[0-9][0-9]}
-			stop=/etc/rc$runlevel.d/K[0-9][0-9]$suffix
-			previous_start=/etc/rc$previous.d/S[0-9][0-9]$suffix
-			#
-			# If there is a start script in the previous level
-			# and _no_ stop script in this level, we don't
-			# have to re-start the service.
-			#
-			[ -f $previous_start ] && [ ! -f $stop ] && continue
+			startup boot
+		else
+			startup $ACTION
 		fi
-		case "$runlevel" in
-			0|6)
-				startup $i stop
-				;;
-			*)
-				startup $i start
-				;;
-		esac
-	done
-  fi
+	else
+		# Now run the START scripts for this runlevel.
+		# Run all scripts with the same level in parallel
+		CURLEVEL=""
+		for s in /etc/rc$runlevel.d/S*
+		do
+			# Extract order value from symlink
+			level=${s#/etc/rc$runlevel.d/S}
+			level=${level%%[a-zA-Z]*}
+			if [ "$level" = "$CURLEVEL" ]
+			then
+				continue
+			fi
+			CURLEVEL=$level
+			SCRIPTS=""
+			for i in /etc/rc$runlevel.d/S$level*
+			do
+				[ ! -f $i ] && continue
 
-#Uncomment to cause psplash to exit manually, otherwise it exits when it sees a VC switch
-if [ "x$runlevel" != "xS" ] && [ ! -x /etc/rc${runlevel}.d/S??xserver-nodm ]; then
-    if type psplash-write >/dev/null 2>&1; then
-        TMPDIR=/mnt/.psplash psplash-write "QUIT" || true
-    	umount -l /mnt/.psplash
-    fi
+				suffix=${i#/etc/rc$runlevel.d/S[0-9][0-9]}
+				if [ "$previous" != N ]
+				then
+					#
+					# Find start script in previous runlevel and
+					# stop script in this runlevel.
+					#
+					stop=/etc/rc$runlevel.d/K[0-9][0-9]$suffix
+					previous_start=/etc/rc$previous.d/S[0-9][0-9]$suffix
+					#
+					# If there is a start script in the previous level
+					# and _no_ stop script in this level, we don't
+					# have to re-start the service.
+					#
+					if [ start = "$ACTION" ] ; then
+						[ -f $previous_start ] && [ ! -f $stop ] && continue
+					else
+						# Workaround for the special
+						# handling of runlevels 0 and 6.
+						previous_stop=/etc/rc$previous.d/K[0-9][0-9]$suffix
+						#
+						# If there is a stop script in the previous level
+						# and _no_ start script there, we don't
+						# have to re-stop the service.
+						#
+						[ -f $previous_stop ] && [ ! -f $previous_start ] && continue
+					fi
+
+				fi
+				SCRIPTS="$SCRIPTS $i"
+			done
+			startup $ACTION $SCRIPTS
+		done
+	fi
 fi
+
+trap - EXIT # Disable emergency handler
+
+exit 0
+
